// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefJet {

  private ColorMapDefJet() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0f, 0f},
        {0.35f, 0f, 0f},
        {0.66f, 1f, 1f},
        {0.89f, 1f, 1f},
        {1f, 0.5f, 0.5f}},
      { // green
        {0.0f, 0f, 0f},
        {0.125f, 0f, 0f},
        {0.375f, 1f, 1f},
        {0.64f, 1f, 1f},
        {0.91f, 0f, 0f},
        {1f, 0f, 0f}},
      { // blue
        {0.0f, 0.5f, 0.5f},
        {0.11f, 1f, 1f},
        {0.34f, 1f, 1f},
        {0.65f, 0f, 0f},
        {1f, 0f, 0f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
