// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefYlorrd {

  private ColorMapDefYlorrd() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 1.0f, 1.0f},
        {0.125f, 1.0f, 1.0f},
        {0.25f, 0.996078431606f, 0.996078431606f},
        {0.375f, 0.996078431606f, 0.996078431606f},
        {0.5f, 0.992156863213f, 0.992156863213f},
        {0.625f, 0.988235294819f, 0.988235294819f},
        {0.75f, 0.890196084976f, 0.890196084976f},
        {0.875f, 0.741176486015f, 0.741176486015f},
        {1.0f, 0.501960813999f, 0.501960813999f}},
      { // green
        {0.0f, 1.0f, 1.0f},
        {0.125f, 0.929411768913f, 0.929411768913f},
        {0.25f, 0.850980401039f, 0.850980401039f},
        {0.375f, 0.698039233685f, 0.698039233685f},
        {0.5f, 0.552941203117f, 0.552941203117f},
        {0.625f, 0.305882364511f, 0.305882364511f},
        {0.75f, 0.101960785687f, 0.101960785687f},
        {0.875f, 0.0f, 0.0f},
        {1.0f, 0.0f, 0.0f}},
      { // blue
        {0.0f, 0.800000011921f, 0.800000011921f},
        {0.125f, 0.627451002598f, 0.627451002598f},
        {0.25f, 0.46274510026f, 0.46274510026f},
        {0.375f, 0.298039227724f, 0.298039227724f},
        {0.5f, 0.235294118524f, 0.235294118524f},
        {0.625f, 0.164705887437f, 0.164705887437f},
        {0.75f, 0.109803922474f, 0.109803922474f},
        {0.875f, 0.149019613862f, 0.149019613862f},
        {1.0f, 0.149019613862f, 0.149019613862f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
