// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefSet3 {

  private ColorMapDefSet3() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.552941203117f, 0.552941203117f},
        {0.0909090909091f, 1.0f, 1.0f},
        {0.181818181818f, 0.745098054409f, 0.745098054409f},
        {0.272727272727f, 0.984313726425f, 0.984313726425f},
        {0.363636363636f, 0.501960813999f, 0.501960813999f},
        {0.454545454545f, 0.992156863213f, 0.992156863213f},
        {0.545454545455f, 0.701960802078f, 0.701960802078f},
        {0.636363636364f, 0.988235294819f, 0.988235294819f},
        {0.727272727273f, 0.850980401039f, 0.850980401039f},
        {0.818181818182f, 0.737254917622f, 0.737254917622f},
        {0.909090909091f, 0.800000011921f, 0.800000011921f},
        {1.0f, 1.0f, 1.0f}},
      { // green
        {0.0f, 0.827450990677f, 0.827450990677f},
        {0.0909090909091f, 1.0f, 1.0f},
        {0.181818181818f, 0.729411780834f, 0.729411780834f},
        {0.272727272727f, 0.501960813999f, 0.501960813999f},
        {0.363636363636f, 0.694117665291f, 0.694117665291f},
        {0.454545454545f, 0.705882370472f, 0.705882370472f},
        {0.545454545455f, 0.870588243008f, 0.870588243008f},
        {0.636363636364f, 0.803921580315f, 0.803921580315f},
        {0.727272727273f, 0.850980401039f, 0.850980401039f},
        {0.818181818182f, 0.501960813999f, 0.501960813999f},
        {0.909090909091f, 0.921568632126f, 0.921568632126f},
        {1.0f, 0.929411768913f, 0.929411768913f}},
      { // blue
        {0.0f, 0.780392169952f, 0.780392169952f},
        {0.0909090909091f, 0.701960802078f, 0.701960802078f},
        {0.181818181818f, 0.854901969433f, 0.854901969433f},
        {0.272727272727f, 0.447058826685f, 0.447058826685f},
        {0.363636363636f, 0.827450990677f, 0.827450990677f},
        {0.454545454545f, 0.384313732386f, 0.384313732386f},
        {0.545454545455f, 0.411764711142f, 0.411764711142f},
        {0.636363636364f, 0.898039221764f, 0.898039221764f},
        {0.727272727273f, 0.850980401039f, 0.850980401039f},
        {0.818181818182f, 0.741176486015f, 0.741176486015f},
        {0.909090909091f, 0.772549033165f, 0.772549033165f},
        {1.0f, 0.435294121504f, 0.435294121504f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
