// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefRdbu {

  private ColorMapDefRdbu() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.403921574354f, 0.403921574354f},
        {0.1f, 0.698039233685f, 0.698039233685f},
        {0.2f, 0.839215695858f, 0.839215695858f},
        {0.3f, 0.956862747669f, 0.956862747669f},
        {0.4f, 0.992156863213f, 0.992156863213f},
        {0.5f, 0.96862745285f, 0.96862745285f},
        {0.6f, 0.819607853889f, 0.819607853889f},
        {0.7f, 0.572549045086f, 0.572549045086f},
        {0.8f, 0.262745112181f, 0.262745112181f},
        {0.9f, 0.129411771894f, 0.129411771894f},
        {1.0f, 0.0196078438312f, 0.0196078438312f}},
      { // green
        {0.0f, 0.0f, 0.0f},
        {0.1f, 0.0941176488996f, 0.0941176488996f},
        {0.2f, 0.376470595598f, 0.376470595598f},
        {0.3f, 0.647058844566f, 0.647058844566f},
        {0.4f, 0.858823537827f, 0.858823537827f},
        {0.5f, 0.96862745285f, 0.96862745285f},
        {0.6f, 0.898039221764f, 0.898039221764f},
        {0.7f, 0.772549033165f, 0.772549033165f},
        {0.8f, 0.57647061348f, 0.57647061348f},
        {0.9f, 0.40000000596f, 0.40000000596f},
        {1.0f, 0.188235297799f, 0.188235297799f}},
      { // blue
        {0.0f, 0.121568627656f, 0.121568627656f},
        {0.1f, 0.168627455831f, 0.168627455831f},
        {0.2f, 0.301960796118f, 0.301960796118f},
        {0.3f, 0.509803950787f, 0.509803950787f},
        {0.4f, 0.780392169952f, 0.780392169952f},
        {0.5f, 0.96862745285f, 0.96862745285f},
        {0.6f, 0.941176474094f, 0.941176474094f},
        {0.7f, 0.870588243008f, 0.870588243008f},
        {0.8f, 0.764705896378f, 0.764705896378f},
        {0.9f, 0.674509823322f, 0.674509823322f},
        {1.0f, 0.380392163992f, 0.380392163992f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
