// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefRdylbu {

  private ColorMapDefRdylbu() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.647058844566f, 0.647058844566f},
        {0.10000000149f, 0.843137264252f, 0.843137264252f},
        {0.20000000298f, 0.956862747669f, 0.956862747669f},
        {0.300000011921f, 0.992156863213f, 0.992156863213f},
        {0.40000000596f, 0.996078431606f, 0.996078431606f},
        {0.5f, 1.0f, 1.0f},
        {0.600000023842f, 0.878431379795f, 0.878431379795f},
        {0.699999988079f, 0.670588254929f, 0.670588254929f},
        {0.800000011921f, 0.454901963472f, 0.454901963472f},
        {0.899999976158f, 0.270588248968f, 0.270588248968f},
        {1.0f, 0.192156866193f, 0.192156866193f}},
      { // green
        {0.0f, 0.0f, 0.0f},
        {0.10000000149f, 0.188235297799f, 0.188235297799f},
        {0.20000000298f, 0.427450984716f, 0.427450984716f},
        {0.300000011921f, 0.68235296011f, 0.68235296011f},
        {0.40000000596f, 0.878431379795f, 0.878431379795f},
        {0.5f, 1.0f, 1.0f},
        {0.600000023842f, 0.952941179276f, 0.952941179276f},
        {0.699999988079f, 0.850980401039f, 0.850980401039f},
        {0.800000011921f, 0.678431391716f, 0.678431391716f},
        {0.899999976158f, 0.458823531866f, 0.458823531866f},
        {1.0f, 0.211764708161f, 0.211764708161f}},
      { // blue
        {0.0f, 0.149019613862f, 0.149019613862f},
        {0.10000000149f, 0.152941182256f, 0.152941182256f},
        {0.20000000298f, 0.262745112181f, 0.262745112181f},
        {0.300000011921f, 0.380392163992f, 0.380392163992f},
        {0.40000000596f, 0.564705908298f, 0.564705908298f},
        {0.5f, 0.749019622803f, 0.749019622803f},
        {0.600000023842f, 0.972549021244f, 0.972549021244f},
        {0.699999988079f, 0.913725495338f, 0.913725495338f},
        {0.800000011921f, 0.819607853889f, 0.819607853889f},
        {0.899999976158f, 0.705882370472f, 0.705882370472f},
        {1.0f, 0.584313750267f, 0.584313750267f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
