// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefPastel1 {

  private ColorMapDefPastel1() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.984313726425f, 0.984313726425f},
        {0.125f, 0.701960802078f, 0.701960802078f},
        {0.25f, 0.800000011921f, 0.800000011921f},
        {0.375f, 0.870588243008f, 0.870588243008f},
        {0.5f, 0.996078431606f, 0.996078431606f},
        {0.625f, 1.0f, 1.0f},
        {0.75f, 0.898039221764f, 0.898039221764f},
        {0.875f, 0.992156863213f, 0.992156863213f},
        {1.0f, 0.949019610882f, 0.949019610882f}},
      { // green
        {0.0f, 0.705882370472f, 0.705882370472f},
        {0.125f, 0.803921580315f, 0.803921580315f},
        {0.25f, 0.921568632126f, 0.921568632126f},
        {0.375f, 0.796078443527f, 0.796078443527f},
        {0.5f, 0.850980401039f, 0.850980401039f},
        {0.625f, 1.0f, 1.0f},
        {0.75f, 0.847058832645f, 0.847058832645f},
        {0.875f, 0.854901969433f, 0.854901969433f},
        {1.0f, 0.949019610882f, 0.949019610882f}},
      { // blue
        {0.0f, 0.68235296011f, 0.68235296011f},
        {0.125f, 0.890196084976f, 0.890196084976f},
        {0.25f, 0.772549033165f, 0.772549033165f},
        {0.375f, 0.89411765337f, 0.89411765337f},
        {0.5f, 0.65098041296f, 0.65098041296f},
        {0.625f, 0.800000011921f, 0.800000011921f},
        {0.75f, 0.741176486015f, 0.741176486015f},
        {0.875f, 0.92549020052f, 0.92549020052f},
        {1.0f, 0.949019610882f, 0.949019610882f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
