// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefYlgnbu {

  private ColorMapDefYlgnbu() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 1.0f, 1.0f},
        {0.125f, 0.929411768913f, 0.929411768913f},
        {0.25f, 0.780392169952f, 0.780392169952f},
        {0.375f, 0.498039215803f, 0.498039215803f},
        {0.5f, 0.254901975393f, 0.254901975393f},
        {0.625f, 0.113725490868f, 0.113725490868f},
        {0.75f, 0.133333340287f, 0.133333340287f},
        {0.875f, 0.145098045468f, 0.145098045468f},
        {1.0f, 0.0313725508749f, 0.0313725508749f}},
      { // green
        {0.0f, 1.0f, 1.0f},
        {0.125f, 0.972549021244f, 0.972549021244f},
        {0.25f, 0.913725495338f, 0.913725495338f},
        {0.375f, 0.803921580315f, 0.803921580315f},
        {0.5f, 0.713725507259f, 0.713725507259f},
        {0.625f, 0.568627476692f, 0.568627476692f},
        {0.75f, 0.368627458811f, 0.368627458811f},
        {0.875f, 0.203921571374f, 0.203921571374f},
        {1.0f, 0.113725490868f, 0.113725490868f}},
      { // blue
        {0.0f, 0.850980401039f, 0.850980401039f},
        {0.125f, 0.694117665291f, 0.694117665291f},
        {0.25f, 0.705882370472f, 0.705882370472f},
        {0.375f, 0.733333349228f, 0.733333349228f},
        {0.5f, 0.768627464771f, 0.768627464771f},
        {0.625f, 0.752941191196f, 0.752941191196f},
        {0.75f, 0.658823549747f, 0.658823549747f},
        {0.875f, 0.580392181873f, 0.580392181873f},
        {1.0f, 0.345098048449f, 0.345098048449f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
