// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefPastel2 {

  private ColorMapDefPastel2() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.701960802078f, 0.701960802078f},
        {0.142857142857f, 0.992156863213f, 0.992156863213f},
        {0.285714285714f, 0.796078443527f, 0.796078443527f},
        {0.428571428571f, 0.956862747669f, 0.956862747669f},
        {0.571428571429f, 0.901960790157f, 0.901960790157f},
        {0.714285714286f, 1.0f, 1.0f},
        {0.857142857143f, 0.945098042488f, 0.945098042488f},
        {1.0f, 0.800000011921f, 0.800000011921f}},
      { // green
        {0.0f, 0.886274516582f, 0.886274516582f},
        {0.142857142857f, 0.803921580315f, 0.803921580315f},
        {0.285714285714f, 0.835294127464f, 0.835294127464f},
        {0.428571428571f, 0.792156875134f, 0.792156875134f},
        {0.571428571429f, 0.960784316063f, 0.960784316063f},
        {0.714285714286f, 0.949019610882f, 0.949019610882f},
        {0.857142857143f, 0.886274516582f, 0.886274516582f},
        {1.0f, 0.800000011921f, 0.800000011921f}},
      { // blue
        {0.0f, 0.803921580315f, 0.803921580315f},
        {0.142857142857f, 0.674509823322f, 0.674509823322f},
        {0.285714285714f, 0.909803926945f, 0.909803926945f},
        {0.428571428571f, 0.89411765337f, 0.89411765337f},
        {0.571428571429f, 0.78823530674f, 0.78823530674f},
        {0.714285714286f, 0.68235296011f, 0.68235296011f},
        {0.857142857143f, 0.800000011921f, 0.800000011921f},
        {1.0f, 0.800000011921f, 0.800000011921f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
