// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefRdylgn {

  private ColorMapDefRdylgn() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.647058844566f, 0.647058844566f},
        {0.1f, 0.843137264252f, 0.843137264252f},
        {0.2f, 0.956862747669f, 0.956862747669f},
        {0.3f, 0.992156863213f, 0.992156863213f},
        {0.4f, 0.996078431606f, 0.996078431606f},
        {0.5f, 1.0f, 1.0f},
        {0.6f, 0.850980401039f, 0.850980401039f},
        {0.7f, 0.65098041296f, 0.65098041296f},
        {0.8f, 0.40000000596f, 0.40000000596f},
        {0.9f, 0.101960785687f, 0.101960785687f},
        {1.0f, 0.0f, 0.0f}},
      { // green
        {0.0f, 0.0f, 0.0f},
        {0.1f, 0.188235297799f, 0.188235297799f},
        {0.2f, 0.427450984716f, 0.427450984716f},
        {0.3f, 0.68235296011f, 0.68235296011f},
        {0.4f, 0.878431379795f, 0.878431379795f},
        {0.5f, 1.0f, 1.0f},
        {0.6f, 0.937254905701f, 0.937254905701f},
        {0.7f, 0.850980401039f, 0.850980401039f},
        {0.8f, 0.741176486015f, 0.741176486015f},
        {0.9f, 0.596078455448f, 0.596078455448f},
        {1.0f, 0.407843142748f, 0.407843142748f}},
      { // blue
        {0.0f, 0.149019613862f, 0.149019613862f},
        {0.1f, 0.152941182256f, 0.152941182256f},
        {0.2f, 0.262745112181f, 0.262745112181f},
        {0.3f, 0.380392163992f, 0.380392163992f},
        {0.4f, 0.54509806633f, 0.54509806633f},
        {0.5f, 0.749019622803f, 0.749019622803f},
        {0.6f, 0.54509806633f, 0.54509806633f},
        {0.7f, 0.415686279535f, 0.415686279535f},
        {0.8f, 0.388235300779f, 0.388235300779f},
        {0.9f, 0.313725501299f, 0.313725501299f},
        {1.0f, 0.215686276555f, 0.215686276555f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
