// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefDark2 {

  private ColorMapDefDark2() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.105882354081f, 0.105882354081f},
        {0.142857142857f, 0.850980401039f, 0.850980401039f},
        {0.285714285714f, 0.458823531866f, 0.458823531866f},
        {0.428571428571f, 0.905882358551f, 0.905882358551f},
        {0.571428571429f, 0.40000000596f, 0.40000000596f},
        {0.714285714286f, 0.901960790157f, 0.901960790157f},
        {0.857142857143f, 0.65098041296f, 0.65098041296f},
        {1.0f, 0.40000000596f, 0.40000000596f}},
      { // green
        {0.0f, 0.61960786581f, 0.61960786581f},
        {0.142857142857f, 0.372549027205f, 0.372549027205f},
        {0.285714285714f, 0.439215689898f, 0.439215689898f},
        {0.428571428571f, 0.160784319043f, 0.160784319043f},
        {0.571428571429f, 0.65098041296f, 0.65098041296f},
        {0.714285714286f, 0.670588254929f, 0.670588254929f},
        {0.857142857143f, 0.46274510026f, 0.46274510026f},
        {1.0f, 0.40000000596f, 0.40000000596f}},
      { // blue
        {0.0f, 0.466666668653f, 0.466666668653f},
        {0.142857142857f, 0.00784313771874f, 0.00784313771874f},
        {0.285714285714f, 0.701960802078f, 0.701960802078f},
        {0.428571428571f, 0.541176497936f, 0.541176497936f},
        {0.571428571429f, 0.117647059262f, 0.117647059262f},
        {0.714285714286f, 0.00784313771874f, 0.00784313771874f},
        {0.857142857143f, 0.113725490868f, 0.113725490868f},
        {1.0f, 0.40000000596f, 0.40000000596f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
