/*
 * Copyright 2016 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package com.google.devtools.depan.maven.eclipse;

import com.google.devtools.depan.eclipse.preferences.PreferencesIds;
import com.google.devtools.depan.maven.graph.ArtifactElement;
import com.google.devtools.depan.maven.graph.PropertyElement;
import com.google.devtools.depan.platform.PlatformResources;

import org.eclipse.core.runtime.Platform;
import org.eclipse.jface.resource.ImageDescriptor;
import org.eclipse.swt.graphics.Image;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.osgi.framework.Bundle;
import org.osgi.framework.BundleContext;

/**
 * The activator class controls the plug-in life cycle.
 * 
 * Initially generated by Eclipse's New PDE Project wizard.
 * @author <a href="mailto:leeca@pnambic.com">Lee Carver</a>
 */
public class MavenActivator extends AbstractUIPlugin {

  /** Plug-in ID used to identify this plug-in. */
  public static final String PLUGIN_ID = "com.google.devtools.depan.maven.ui";

  /**
   * Bundle that is responsible for storing the resources for this plug-in.
   */
  public static final Bundle BUNDLE = Platform.getBundle(PLUGIN_ID);

  /**
   * Prefix to use for preferences.
   */
  public static final String MVN_PREF_PREFIX =
      PreferencesIds.PREFIX + "maven_";

  // The shared instance
  private static MavenActivator plugin;

  /**
   * The constructor
   */
  public MavenActivator() {
  }

  @Override
  public void start(BundleContext context) throws Exception {
    super.start(context);
    plugin = this;
  }

  @Override
  public void stop(BundleContext context) throws Exception {
    plugin = null;
    super.stop(context);
  }

  /**
   * Returns the shared instance
   *
   * @return the shared instance
   */
  public static MavenActivator getDefault() {
    return plugin;
  }

  /////////////////////////////////////
  // Plugin Images 

  /**
   * {@link ImageDescriptor} for {@link ArtifactElement}s.
   */
  public static final ImageDescriptor IMAGE_DESC_MAVEN =
      MavenActivator.getImageDescriptor("icons/eclipse/maven_icon.png");

  /**
   * {@link ImageDescriptor} for {@link PropertyElement}s.
   */
  public static final ImageDescriptor IMAGE_DESC_PROPERTY =
      MavenActivator.getImageDescriptor("icons/eclipse/prop_icon_16x16.png");

  /**
   * {@link Image} object for {@link ArtifactElement}s.
   */
  public static final Image IMAGE_MAVEN = MavenActivator.getImage(IMAGE_DESC_MAVEN);

  /**
   * {@link Image} object for {@link PropertyElement}s.
   */
  public static final Image IMAGE_PROPERTY = MavenActivator.getImage(IMAGE_DESC_PROPERTY);

  private static ImageDescriptor getImageDescriptor(String path) {
    return AbstractUIPlugin.imageDescriptorFromPlugin(PLUGIN_ID, path);
  }

  private static Image getImage(ImageDescriptor descriptor) {
    return PlatformResources.getImage(descriptor);
  }
}
