// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefPiyg {

  private ColorMapDefPiyg() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.556862771511f, 0.556862771511f},
        {0.1f, 0.772549033165f, 0.772549033165f},
        {0.2f, 0.870588243008f, 0.870588243008f},
        {0.3f, 0.945098042488f, 0.945098042488f},
        {0.4f, 0.992156863213f, 0.992156863213f},
        {0.5f, 0.96862745285f, 0.96862745285f},
        {0.6f, 0.901960790157f, 0.901960790157f},
        {0.7f, 0.721568644047f, 0.721568644047f},
        {0.8f, 0.498039215803f, 0.498039215803f},
        {0.9f, 0.301960796118f, 0.301960796118f},
        {1.0f, 0.152941182256f, 0.152941182256f}},
      { // green
        {0.0f, 0.00392156885937f, 0.00392156885937f},
        {0.1f, 0.105882354081f, 0.105882354081f},
        {0.2f, 0.466666668653f, 0.466666668653f},
        {0.3f, 0.713725507259f, 0.713725507259f},
        {0.4f, 0.878431379795f, 0.878431379795f},
        {0.5f, 0.96862745285f, 0.96862745285f},
        {0.6f, 0.960784316063f, 0.960784316063f},
        {0.7f, 0.882352948189f, 0.882352948189f},
        {0.8f, 0.737254917622f, 0.737254917622f},
        {0.9f, 0.572549045086f, 0.572549045086f},
        {1.0f, 0.392156869173f, 0.392156869173f}},
      { // blue
        {0.0f, 0.321568638086f, 0.321568638086f},
        {0.1f, 0.490196079016f, 0.490196079016f},
        {0.2f, 0.68235296011f, 0.68235296011f},
        {0.3f, 0.854901969433f, 0.854901969433f},
        {0.4f, 0.937254905701f, 0.937254905701f},
        {0.5f, 0.96862745285f, 0.96862745285f},
        {0.6f, 0.815686285496f, 0.815686285496f},
        {0.7f, 0.525490224361f, 0.525490224361f},
        {0.8f, 0.254901975393f, 0.254901975393f},
        {0.9f, 0.129411771894f, 0.129411771894f},
        {1.0f, 0.0980392172933f, 0.0980392172933f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
