// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefPurd {

  private ColorMapDefPurd() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.96862745285f, 0.96862745285f},
        {0.125f, 0.905882358551f, 0.905882358551f},
        {0.25f, 0.831372559071f, 0.831372559071f},
        {0.375f, 0.78823530674f, 0.78823530674f},
        {0.5f, 0.874509811401f, 0.874509811401f},
        {0.625f, 0.905882358551f, 0.905882358551f},
        {0.75f, 0.807843148708f, 0.807843148708f},
        {0.875f, 0.596078455448f, 0.596078455448f},
        {1.0f, 0.403921574354f, 0.403921574354f}},
      { // green
        {0.0f, 0.956862747669f, 0.956862747669f},
        {0.125f, 0.882352948189f, 0.882352948189f},
        {0.25f, 0.72549021244f, 0.72549021244f},
        {0.375f, 0.580392181873f, 0.580392181873f},
        {0.5f, 0.396078437567f, 0.396078437567f},
        {0.625f, 0.160784319043f, 0.160784319043f},
        {0.75f, 0.0705882385373f, 0.0705882385373f},
        {0.875f, 0.0f, 0.0f},
        {1.0f, 0.0f, 0.0f}},
      { // blue
        {0.0f, 0.976470589638f, 0.976470589638f},
        {0.125f, 0.937254905701f, 0.937254905701f},
        {0.25f, 0.854901969433f, 0.854901969433f},
        {0.375f, 0.780392169952f, 0.780392169952f},
        {0.5f, 0.690196096897f, 0.690196096897f},
        {0.625f, 0.541176497936f, 0.541176497936f},
        {0.75f, 0.337254911661f, 0.337254911661f},
        {0.875f, 0.262745112181f, 0.262745112181f},
        {1.0f, 0.121568627656f, 0.121568627656f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
