// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefSet1 {

  private ColorMapDefSet1() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.89411765337f, 0.89411765337f},
        {0.125f, 0.215686276555f, 0.215686276555f},
        {0.25f, 0.301960796118f, 0.301960796118f},
        {0.375f, 0.596078455448f, 0.596078455448f},
        {0.5f, 1.0f, 1.0f},
        {0.625f, 1.0f, 1.0f},
        {0.75f, 0.65098041296f, 0.65098041296f},
        {0.875f, 0.96862745285f, 0.96862745285f},
        {1.0f, 0.600000023842f, 0.600000023842f}},
      { // green
        {0.0f, 0.101960785687f, 0.101960785687f},
        {0.125f, 0.494117647409f, 0.494117647409f},
        {0.25f, 0.686274528503f, 0.686274528503f},
        {0.375f, 0.305882364511f, 0.305882364511f},
        {0.5f, 0.498039215803f, 0.498039215803f},
        {0.625f, 1.0f, 1.0f},
        {0.75f, 0.337254911661f, 0.337254911661f},
        {0.875f, 0.505882382393f, 0.505882382393f},
        {1.0f, 0.600000023842f, 0.600000023842f}},
      { // blue
        {0.0f, 0.109803922474f, 0.109803922474f},
        {0.125f, 0.721568644047f, 0.721568644047f},
        {0.25f, 0.290196090937f, 0.290196090937f},
        {0.375f, 0.639215707779f, 0.639215707779f},
        {0.5f, 0.0f, 0.0f},
        {0.625f, 0.20000000298f, 0.20000000298f},
        {0.75f, 0.156862750649f, 0.156862750649f},
        {0.875f, 0.749019622803f, 0.749019622803f},
        {1.0f, 0.600000023842f, 0.600000023842f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
