// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefOrrd {

  private ColorMapDefOrrd() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 1.0f, 1.0f},
        {0.125f, 0.996078431606f, 0.996078431606f},
        {0.25f, 0.992156863213f, 0.992156863213f},
        {0.375f, 0.992156863213f, 0.992156863213f},
        {0.5f, 0.988235294819f, 0.988235294819f},
        {0.625f, 0.937254905701f, 0.937254905701f},
        {0.75f, 0.843137264252f, 0.843137264252f},
        {0.875f, 0.701960802078f, 0.701960802078f},
        {1.0f, 0.498039215803f, 0.498039215803f}},
      { // green
        {0.0f, 0.96862745285f, 0.96862745285f},
        {0.125f, 0.909803926945f, 0.909803926945f},
        {0.25f, 0.831372559071f, 0.831372559071f},
        {0.375f, 0.733333349228f, 0.733333349228f},
        {0.5f, 0.552941203117f, 0.552941203117f},
        {0.625f, 0.396078437567f, 0.396078437567f},
        {0.75f, 0.188235297799f, 0.188235297799f},
        {0.875f, 0.0f, 0.0f},
        {1.0f, 0.0f, 0.0f}},
      { // blue
        {0.0f, 0.92549020052f, 0.92549020052f},
        {0.125f, 0.784313738346f, 0.784313738346f},
        {0.25f, 0.61960786581f, 0.61960786581f},
        {0.375f, 0.517647087574f, 0.517647087574f},
        {0.5f, 0.349019616842f, 0.349019616842f},
        {0.625f, 0.282352954149f, 0.282352954149f},
        {0.75f, 0.121568627656f, 0.121568627656f},
        {0.875f, 0.0f, 0.0f},
        {1.0f, 0.0f, 0.0f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
