// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefPubu {

  private ColorMapDefPubu() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 1.0f, 1.0f},
        {0.125f, 0.92549020052f, 0.92549020052f},
        {0.25f, 0.815686285496f, 0.815686285496f},
        {0.375f, 0.65098041296f, 0.65098041296f},
        {0.5f, 0.454901963472f, 0.454901963472f},
        {0.625f, 0.211764708161f, 0.211764708161f},
        {0.75f, 0.0196078438312f, 0.0196078438312f},
        {0.875f, 0.0156862754375f, 0.0156862754375f},
        {1.0f, 0.00784313771874f, 0.00784313771874f}},
      { // green
        {0.0f, 0.96862745285f, 0.96862745285f},
        {0.125f, 0.905882358551f, 0.905882358551f},
        {0.25f, 0.819607853889f, 0.819607853889f},
        {0.375f, 0.741176486015f, 0.741176486015f},
        {0.5f, 0.662745118141f, 0.662745118141f},
        {0.625f, 0.564705908298f, 0.564705908298f},
        {0.75f, 0.439215689898f, 0.439215689898f},
        {0.875f, 0.352941185236f, 0.352941185236f},
        {1.0f, 0.219607844949f, 0.219607844949f}},
      { // blue
        {0.0f, 0.984313726425f, 0.984313726425f},
        {0.125f, 0.949019610882f, 0.949019610882f},
        {0.25f, 0.901960790157f, 0.901960790157f},
        {0.375f, 0.858823537827f, 0.858823537827f},
        {0.5f, 0.811764717102f, 0.811764717102f},
        {0.625f, 0.752941191196f, 0.752941191196f},
        {0.75f, 0.690196096897f, 0.690196096897f},
        {0.875f, 0.552941203117f, 0.552941203117f},
        {1.0f, 0.345098048449f, 0.345098048449f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
