// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefReds {

  private ColorMapDefReds() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 1.0f, 1.0f},
        {0.125f, 0.996078431606f, 0.996078431606f},
        {0.25f, 0.988235294819f, 0.988235294819f},
        {0.375f, 0.988235294819f, 0.988235294819f},
        {0.5f, 0.984313726425f, 0.984313726425f},
        {0.625f, 0.937254905701f, 0.937254905701f},
        {0.75f, 0.796078443527f, 0.796078443527f},
        {0.875f, 0.647058844566f, 0.647058844566f},
        {1.0f, 0.403921574354f, 0.403921574354f}},
      { // green
        {0.0f, 0.960784316063f, 0.960784316063f},
        {0.125f, 0.878431379795f, 0.878431379795f},
        {0.25f, 0.733333349228f, 0.733333349228f},
        {0.375f, 0.572549045086f, 0.572549045086f},
        {0.5f, 0.415686279535f, 0.415686279535f},
        {0.625f, 0.23137255013f, 0.23137255013f},
        {0.75f, 0.0941176488996f, 0.0941176488996f},
        {0.875f, 0.0588235296309f, 0.0588235296309f},
        {1.0f, 0.0f, 0.0f}},
      { // blue
        {0.0f, 0.941176474094f, 0.941176474094f},
        {0.125f, 0.823529422283f, 0.823529422283f},
        {0.25f, 0.631372570992f, 0.631372570992f},
        {0.375f, 0.447058826685f, 0.447058826685f},
        {0.5f, 0.290196090937f, 0.290196090937f},
        {0.625f, 0.172549024224f, 0.172549024224f},
        {0.75f, 0.113725490868f, 0.113725490868f},
        {0.875f, 0.0823529437184f, 0.0823529437184f},
        {1.0f, 0.0509803928435f, 0.0509803928435f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
