// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefPaired {

  private ColorMapDefPaired() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.65098041296f, 0.65098041296f},
        {0.0909090909091f, 0.121568627656f, 0.121568627656f},
        {0.181818181818f, 0.698039233685f, 0.698039233685f},
        {0.272727272727f, 0.20000000298f, 0.20000000298f},
        {0.363636363636f, 0.984313726425f, 0.984313726425f},
        {0.454545454545f, 0.890196084976f, 0.890196084976f},
        {0.545454545455f, 0.992156863213f, 0.992156863213f},
        {0.636363636364f, 1.0f, 1.0f},
        {0.727272727273f, 0.792156875134f, 0.792156875134f},
        {0.818181818182f, 0.415686279535f, 0.415686279535f},
        {0.909090909091f, 1.0f, 1.0f},
        {1.0f, 0.694117665291f, 0.694117665291f}},
      { // green
        {0.0f, 0.807843148708f, 0.807843148708f},
        {0.0909090909091f, 0.470588237047f, 0.470588237047f},
        {0.181818181818f, 0.874509811401f, 0.874509811401f},
        {0.272727272727f, 0.627451002598f, 0.627451002598f},
        {0.363636363636f, 0.603921592236f, 0.603921592236f},
        {0.454545454545f, 0.101960785687f, 0.101960785687f},
        {0.545454545455f, 0.749019622803f, 0.749019622803f},
        {0.636363636364f, 0.498039215803f, 0.498039215803f},
        {0.727272727273f, 0.698039233685f, 0.698039233685f},
        {0.818181818182f, 0.239215686917f, 0.239215686917f},
        {0.909090909091f, 1.0f, 1.0f},
        {1.0f, 0.349019616842f, 0.349019616842f}},
      { // blue
        {0.0f, 0.890196084976f, 0.890196084976f},
        {0.0909090909091f, 0.705882370472f, 0.705882370472f},
        {0.181818181818f, 0.541176497936f, 0.541176497936f},
        {0.272727272727f, 0.172549024224f, 0.172549024224f},
        {0.363636363636f, 0.600000023842f, 0.600000023842f},
        {0.454545454545f, 0.109803922474f, 0.109803922474f},
        {0.545454545455f, 0.435294121504f, 0.435294121504f},
        {0.636363636364f, 0.0f, 0.0f},
        {0.727272727273f, 0.839215695858f, 0.839215695858f},
        {0.818181818182f, 0.603921592236f, 0.603921592236f},
        {0.909090909091f, 0.600000023842f, 0.600000023842f},
        {1.0f, 0.156862750649f, 0.156862750649f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
