// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefPrgn {

  private ColorMapDefPrgn() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.250980407f, 0.250980407f},
        {0.1f, 0.46274510026f, 0.46274510026f},
        {0.2f, 0.600000023842f, 0.600000023842f},
        {0.3f, 0.760784327984f, 0.760784327984f},
        {0.4f, 0.905882358551f, 0.905882358551f},
        {0.5f, 0.96862745285f, 0.96862745285f},
        {0.6f, 0.850980401039f, 0.850980401039f},
        {0.7f, 0.65098041296f, 0.65098041296f},
        {0.8f, 0.352941185236f, 0.352941185236f},
        {0.9f, 0.105882354081f, 0.105882354081f},
        {1.0f, 0.0f, 0.0f}},
      { // green
        {0.0f, 0.0f, 0.0f},
        {0.1f, 0.164705887437f, 0.164705887437f},
        {0.2f, 0.439215689898f, 0.439215689898f},
        {0.3f, 0.647058844566f, 0.647058844566f},
        {0.4f, 0.831372559071f, 0.831372559071f},
        {0.5f, 0.96862745285f, 0.96862745285f},
        {0.6f, 0.941176474094f, 0.941176474094f},
        {0.7f, 0.858823537827f, 0.858823537827f},
        {0.8f, 0.68235296011f, 0.68235296011f},
        {0.9f, 0.470588237047f, 0.470588237047f},
        {1.0f, 0.266666680574f, 0.266666680574f}},
      { // blue
        {0.0f, 0.29411765933f, 0.29411765933f},
        {0.1f, 0.51372551918f, 0.51372551918f},
        {0.2f, 0.670588254929f, 0.670588254929f},
        {0.3f, 0.811764717102f, 0.811764717102f},
        {0.4f, 0.909803926945f, 0.909803926945f},
        {0.5f, 0.96862745285f, 0.96862745285f},
        {0.6f, 0.827450990677f, 0.827450990677f},
        {0.7f, 0.627451002598f, 0.627451002598f},
        {0.8f, 0.380392163992f, 0.380392163992f},
        {0.9f, 0.215686276555f, 0.215686276555f},
        {1.0f, 0.105882354081f, 0.105882354081f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
