// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefBupu {

  private ColorMapDefBupu() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.96862745285f, 0.96862745285f},
        {0.125f, 0.878431379795f, 0.878431379795f},
        {0.25f, 0.749019622803f, 0.749019622803f},
        {0.375f, 0.61960786581f, 0.61960786581f},
        {0.5f, 0.549019634724f, 0.549019634724f},
        {0.625f, 0.549019634724f, 0.549019634724f},
        {0.75f, 0.533333361149f, 0.533333361149f},
        {0.875f, 0.505882382393f, 0.505882382393f},
        {1.0f, 0.301960796118f, 0.301960796118f}},
      { // green
        {0.0f, 0.988235294819f, 0.988235294819f},
        {0.125f, 0.92549020052f, 0.92549020052f},
        {0.25f, 0.827450990677f, 0.827450990677f},
        {0.375f, 0.737254917622f, 0.737254917622f},
        {0.5f, 0.588235318661f, 0.588235318661f},
        {0.625f, 0.419607847929f, 0.419607847929f},
        {0.75f, 0.254901975393f, 0.254901975393f},
        {0.875f, 0.0588235296309f, 0.0588235296309f},
        {1.0f, 0.0f, 0.0f}},
      { // blue
        {0.0f, 0.992156863213f, 0.992156863213f},
        {0.125f, 0.956862747669f, 0.956862747669f},
        {0.25f, 0.901960790157f, 0.901960790157f},
        {0.375f, 0.854901969433f, 0.854901969433f},
        {0.5f, 0.776470601559f, 0.776470601559f},
        {0.625f, 0.694117665291f, 0.694117665291f},
        {0.75f, 0.615686297417f, 0.615686297417f},
        {0.875f, 0.486274510622f, 0.486274510622f},
        {1.0f, 0.29411765933f, 0.29411765933f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
