// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefYlorbr {

  private ColorMapDefYlorbr() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 1.0f, 1.0f},
        {0.125f, 1.0f, 1.0f},
        {0.25f, 0.996078431606f, 0.996078431606f},
        {0.375f, 0.996078431606f, 0.996078431606f},
        {0.5f, 0.996078431606f, 0.996078431606f},
        {0.625f, 0.92549020052f, 0.92549020052f},
        {0.75f, 0.800000011921f, 0.800000011921f},
        {0.875f, 0.600000023842f, 0.600000023842f},
        {1.0f, 0.40000000596f, 0.40000000596f}},
      { // green
        {0.0f, 1.0f, 1.0f},
        {0.125f, 0.96862745285f, 0.96862745285f},
        {0.25f, 0.890196084976f, 0.890196084976f},
        {0.375f, 0.768627464771f, 0.768627464771f},
        {0.5f, 0.600000023842f, 0.600000023842f},
        {0.625f, 0.439215689898f, 0.439215689898f},
        {0.75f, 0.298039227724f, 0.298039227724f},
        {0.875f, 0.203921571374f, 0.203921571374f},
        {1.0f, 0.145098045468f, 0.145098045468f}},
      { // blue
        {0.0f, 0.898039221764f, 0.898039221764f},
        {0.125f, 0.737254917622f, 0.737254917622f},
        {0.25f, 0.568627476692f, 0.568627476692f},
        {0.375f, 0.309803932905f, 0.309803932905f},
        {0.5f, 0.160784319043f, 0.160784319043f},
        {0.625f, 0.0784313753247f, 0.0784313753247f},
        {0.75f, 0.00784313771874f, 0.00784313771874f},
        {0.875f, 0.0156862754375f, 0.0156862754375f},
        {1.0f, 0.0235294122249f, 0.0235294122249f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
