// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefGreens {

  private ColorMapDefGreens() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.96862745285f, 0.96862745285f},
        {0.125f, 0.898039221764f, 0.898039221764f},
        {0.25f, 0.780392169952f, 0.780392169952f},
        {0.375f, 0.631372570992f, 0.631372570992f},
        {0.5f, 0.454901963472f, 0.454901963472f},
        {0.625f, 0.254901975393f, 0.254901975393f},
        {0.75f, 0.137254908681f, 0.137254908681f},
        {0.875f, 0.0f, 0.0f},
        {1.0f, 0.0f, 0.0f}},
      { // green
        {0.0f, 0.988235294819f, 0.988235294819f},
        {0.125f, 0.960784316063f, 0.960784316063f},
        {0.25f, 0.913725495338f, 0.913725495338f},
        {0.375f, 0.850980401039f, 0.850980401039f},
        {0.5f, 0.768627464771f, 0.768627464771f},
        {0.625f, 0.670588254929f, 0.670588254929f},
        {0.75f, 0.54509806633f, 0.54509806633f},
        {0.875f, 0.427450984716f, 0.427450984716f},
        {1.0f, 0.266666680574f, 0.266666680574f}},
      { // blue
        {0.0f, 0.960784316063f, 0.960784316063f},
        {0.125f, 0.878431379795f, 0.878431379795f},
        {0.25f, 0.752941191196f, 0.752941191196f},
        {0.375f, 0.607843160629f, 0.607843160629f},
        {0.5f, 0.46274510026f, 0.46274510026f},
        {0.625f, 0.364705890417f, 0.364705890417f},
        {0.75f, 0.270588248968f, 0.270588248968f},
        {0.875f, 0.172549024224f, 0.172549024224f},
        {1.0f, 0.105882354081f, 0.105882354081f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
