// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefBrbg {

  private ColorMapDefBrbg() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.329411774874f, 0.329411774874f},
        {0.1f, 0.549019634724f, 0.549019634724f},
        {0.2f, 0.749019622803f, 0.749019622803f},
        {0.3f, 0.874509811401f, 0.874509811401f},
        {0.4f, 0.964705884457f, 0.964705884457f},
        {0.5f, 0.960784316063f, 0.960784316063f},
        {0.6f, 0.780392169952f, 0.780392169952f},
        {0.7f, 0.501960813999f, 0.501960813999f},
        {0.8f, 0.207843139768f, 0.207843139768f},
        {0.9f, 0.00392156885937f, 0.00392156885937f},
        {1.0f, 0.0f, 0.0f}},
      { // green
        {0.0f, 0.188235297799f, 0.188235297799f},
        {0.1f, 0.317647069693f, 0.317647069693f},
        {0.2f, 0.505882382393f, 0.505882382393f},
        {0.3f, 0.760784327984f, 0.760784327984f},
        {0.4f, 0.909803926945f, 0.909803926945f},
        {0.5f, 0.960784316063f, 0.960784316063f},
        {0.6f, 0.917647063732f, 0.917647063732f},
        {0.7f, 0.803921580315f, 0.803921580315f},
        {0.8f, 0.592156887054f, 0.592156887054f},
        {0.9f, 0.40000000596f, 0.40000000596f},
        {1.0f, 0.235294118524f, 0.235294118524f}},
      { // blue
        {0.0f, 0.0196078438312f, 0.0196078438312f},
        {0.1f, 0.0392156876624f, 0.0392156876624f},
        {0.2f, 0.176470592618f, 0.176470592618f},
        {0.3f, 0.490196079016f, 0.490196079016f},
        {0.4f, 0.764705896378f, 0.764705896378f},
        {0.5f, 0.960784316063f, 0.960784316063f},
        {0.6f, 0.898039221764f, 0.898039221764f},
        {0.7f, 0.75686275959f, 0.75686275959f},
        {0.8f, 0.560784339905f, 0.560784339905f},
        {0.9f, 0.368627458811f, 0.368627458811f},
        {1.0f, 0.188235297799f, 0.188235297799f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
