// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;
import java.util.HashMap;
import java.util.Set;

public final class ColorMapDef {

  private ColorMapDef() { }

  private static HashMap<String, float[][][]> map =
      new HashMap<String, float[][][]>();
  static {
    map.put("Accent", ColorMapDefAccent.CM);
    map.put("Blues", ColorMapDefBlues.CM);
    map.put("BrBG", ColorMapDefBrbg.CM);
    map.put("BuGn", ColorMapDefBugn.CM);
    map.put("BuPu", ColorMapDefBupu.CM);
    map.put("Dark2", ColorMapDefDark2.CM);
    map.put("GnBu", ColorMapDefGnbu.CM);
    map.put("Greens", ColorMapDefGreens.CM);
    map.put("Greys", ColorMapDefGreys.CM);
    map.put("OrRd", ColorMapDefOrrd.CM);
    map.put("Oranges", ColorMapDefOranges.CM);
    map.put("PRGn", ColorMapDefPrgn.CM);
    map.put("Paired", ColorMapDefPaired.CM);
    map.put("Pastel1", ColorMapDefPastel1.CM);
    map.put("Pastel2", ColorMapDefPastel2.CM);
    map.put("PiYG", ColorMapDefPiyg.CM);
    map.put("PuBu", ColorMapDefPubu.CM);
    map.put("PuBuGn", ColorMapDefPubugn.CM);
    map.put("PuOr", ColorMapDefPuor.CM);
    map.put("PuRd", ColorMapDefPurd.CM);
    map.put("Purples", ColorMapDefPurples.CM);
    map.put("RdBu", ColorMapDefRdbu.CM);
    map.put("RdGy", ColorMapDefRdgy.CM);
    map.put("RdPu", ColorMapDefRdpu.CM);
    map.put("RdYlBu", ColorMapDefRdylbu.CM);
    map.put("RdYlGn", ColorMapDefRdylgn.CM);
    map.put("Reds", ColorMapDefReds.CM);
    map.put("Set1", ColorMapDefSet1.CM);
    map.put("Set2", ColorMapDefSet2.CM);
    map.put("Set3", ColorMapDefSet3.CM);
    map.put("Spectral", ColorMapDefSpectral.CM);
    map.put("YlGn", ColorMapDefYlgn.CM);
    map.put("YlGnBu", ColorMapDefYlgnbu.CM);
    map.put("YlOrBr", ColorMapDefYlorbr.CM);
    map.put("YlOrRd", ColorMapDefYlorrd.CM);
    map.put("autumn", ColorMapDefAutumn.CM);
    map.put("binary", ColorMapDefBinary.CM);
    map.put("bone", ColorMapDefBone.CM);
    map.put("cool", ColorMapDefCool.CM);
    map.put("copper", ColorMapDefCopper.CM);
    map.put("flag", ColorMapDefFlag.CM);
    map.put("gist_earth", ColorMapDefGistEarth.CM);
    map.put("gist_gray", ColorMapDefGistGray.CM);
    map.put("gist_heat", ColorMapDefGistHeat.CM);
    map.put("gist_ncar", ColorMapDefGistNcar.CM);
    map.put("gist_rainbow", ColorMapDefGistRainbow.CM);
    map.put("gist_stern", ColorMapDefGistStern.CM);
    map.put("gist_yarg", ColorMapDefGistYarg.CM);
    map.put("gray", ColorMapDefGray.CM);
    map.put("hot", ColorMapDefHot.CM);
    map.put("hsv", ColorMapDefHsv.CM);
    map.put("jet", ColorMapDefJet.CM);
    map.put("pink", ColorMapDefPink.CM);
    map.put("prism", ColorMapDefPrism.CM);
    map.put("spectral", ColorMapDefSpectral.CM);
    map.put("spring", ColorMapDefSpring.CM);
    map.put("summer", ColorMapDefSummer.CM);
    map.put("winter", ColorMapDefWinter.CM);
  }

  public static float[][][] getColorMapDef(String name) {
    return map.get(name);
  }

  public static Set<String> getColorMapNames() {
    return map.keySet();
  }

}
