// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefSpectral {

  private ColorMapDefSpectral() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.0f, 0.0f},
        {0.05f, 0.4667f, 0.4667f},
        {0.1f, 0.5333f, 0.5333f},
        {0.15f, 0.0f, 0.0f},
        {0.2f, 0.0f, 0.0f},
        {0.25f, 0.0f, 0.0f},
        {0.3f, 0.0f, 0.0f},
        {0.35f, 0.0f, 0.0f},
        {0.4f, 0.0f, 0.0f},
        {0.45f, 0.0f, 0.0f},
        {0.5f, 0.0f, 0.0f},
        {0.55f, 0.0f, 0.0f},
        {0.6f, 0.0f, 0.0f},
        {0.65f, 0.7333f, 0.7333f},
        {0.7f, 0.9333f, 0.9333f},
        {0.75f, 1.0f, 1.0f},
        {0.8f, 1.0f, 1.0f},
        {0.85f, 1.0f, 1.0f},
        {0.9f, 0.8667f, 0.8667f},
        {0.95f, 0.8f, 0.8f},
        {1.0f, 0.8f, 0.8f}},
      { // green
        {0.0f, 0.0f, 0.0f},
        {0.05f, 0.0f, 0.0f},
        {0.1f, 0.0f, 0.0f},
        {0.15f, 0.0f, 0.0f},
        {0.2f, 0.0f, 0.0f},
        {0.25f, 0.4667f, 0.4667f},
        {0.3f, 0.6f, 0.6f},
        {0.35f, 0.6667f, 0.6667f},
        {0.4f, 0.6667f, 0.6667f},
        {0.45f, 0.6f, 0.6f},
        {0.5f, 0.7333f, 0.7333f},
        {0.55f, 0.8667f, 0.8667f},
        {0.6f, 1.0f, 1.0f},
        {0.65f, 1.0f, 1.0f},
        {0.7f, 0.9333f, 0.9333f},
        {0.75f, 0.8f, 0.8f},
        {0.8f, 0.6f, 0.6f},
        {0.85f, 0.0f, 0.0f},
        {0.9f, 0.0f, 0.0f},
        {0.95f, 0.0f, 0.0f},
        {1.0f, 0.8f, 0.8f}},
      { // blue
        {0.0f, 0.0f, 0.0f},
        {0.05f, 0.5333f, 0.5333f},
        {0.1f, 0.6f, 0.6f},
        {0.15f, 0.6667f, 0.6667f},
        {0.2f, 0.8667f, 0.8667f},
        {0.25f, 0.8667f, 0.8667f},
        {0.3f, 0.8667f, 0.8667f},
        {0.35f, 0.6667f, 0.6667f},
        {0.4f, 0.5333f, 0.5333f},
        {0.45f, 0.0f, 0.0f},
        {0.5f, 0.0f, 0.0f},
        {0.55f, 0.0f, 0.0f},
        {0.6f, 0.0f, 0.0f},
        {0.65f, 0.0f, 0.0f},
        {0.7f, 0.0f, 0.0f},
        {0.75f, 0.0f, 0.0f},
        {0.8f, 0.0f, 0.0f},
        {0.85f, 0.0f, 0.0f},
        {0.9f, 0.0f, 0.0f},
        {0.95f, 0.0f, 0.0f},
        {1.0f, 0.8f, 0.8f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
