// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefOranges {

  private ColorMapDefOranges() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 1.0f, 1.0f},
        {0.125f, 0.996078431606f, 0.996078431606f},
        {0.25f, 0.992156863213f, 0.992156863213f},
        {0.375f, 0.992156863213f, 0.992156863213f},
        {0.5f, 0.992156863213f, 0.992156863213f},
        {0.625f, 0.945098042488f, 0.945098042488f},
        {0.75f, 0.850980401039f, 0.850980401039f},
        {0.875f, 0.65098041296f, 0.65098041296f},
        {1.0f, 0.498039215803f, 0.498039215803f}},
      { // green
        {0.0f, 0.960784316063f, 0.960784316063f},
        {0.125f, 0.901960790157f, 0.901960790157f},
        {0.25f, 0.815686285496f, 0.815686285496f},
        {0.375f, 0.68235296011f, 0.68235296011f},
        {0.5f, 0.552941203117f, 0.552941203117f},
        {0.625f, 0.411764711142f, 0.411764711142f},
        {0.75f, 0.282352954149f, 0.282352954149f},
        {0.875f, 0.211764708161f, 0.211764708161f},
        {1.0f, 0.152941182256f, 0.152941182256f}},
      { // blue
        {0.0f, 0.921568632126f, 0.921568632126f},
        {0.125f, 0.807843148708f, 0.807843148708f},
        {0.25f, 0.635294139385f, 0.635294139385f},
        {0.375f, 0.419607847929f, 0.419607847929f},
        {0.5f, 0.235294118524f, 0.235294118524f},
        {0.625f, 0.074509806931f, 0.074509806931f},
        {0.75f, 0.00392156885937f, 0.00392156885937f},
        {0.875f, 0.0117647061124f, 0.0117647061124f},
        {1.0f, 0.0156862754375f, 0.0156862754375f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
