// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefAccent {

  private ColorMapDefAccent() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.498039215803f, 0.498039215803f},
        {0.142857142857f, 0.745098054409f, 0.745098054409f},
        {0.285714285714f, 0.992156863213f, 0.992156863213f},
        {0.428571428571f, 1.0f, 1.0f},
        {0.571428571429f, 0.219607844949f, 0.219607844949f},
        {0.714285714286f, 0.941176474094f, 0.941176474094f},
        {0.857142857143f, 0.749019622803f, 0.749019622803f},
        {1.0f, 0.40000000596f, 0.40000000596f}},
      { // green
        {0.0f, 0.78823530674f, 0.78823530674f},
        {0.142857142857f, 0.68235296011f, 0.68235296011f},
        {0.285714285714f, 0.752941191196f, 0.752941191196f},
        {0.428571428571f, 1.0f, 1.0f},
        {0.571428571429f, 0.423529416323f, 0.423529416323f},
        {0.714285714286f, 0.00784313771874f, 0.00784313771874f},
        {0.857142857143f, 0.35686275363f, 0.35686275363f},
        {1.0f, 0.40000000596f, 0.40000000596f}},
      { // blue
        {0.0f, 0.498039215803f, 0.498039215803f},
        {0.142857142857f, 0.831372559071f, 0.831372559071f},
        {0.285714285714f, 0.525490224361f, 0.525490224361f},
        {0.428571428571f, 0.600000023842f, 0.600000023842f},
        {0.571428571429f, 0.690196096897f, 0.690196096897f},
        {0.714285714286f, 0.498039215803f, 0.498039215803f},
        {0.857142857143f, 0.0901960805058f, 0.0901960805058f},
        {1.0f, 0.40000000596f, 0.40000000596f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
