// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefBlues {

  private ColorMapDefBlues() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.96862745285f, 0.96862745285f},
        {0.125f, 0.870588243008f, 0.870588243008f},
        {0.25f, 0.776470601559f, 0.776470601559f},
        {0.375f, 0.61960786581f, 0.61960786581f},
        {0.5f, 0.419607847929f, 0.419607847929f},
        {0.625f, 0.258823543787f, 0.258823543787f},
        {0.75f, 0.129411771894f, 0.129411771894f},
        {0.875f, 0.0313725508749f, 0.0313725508749f},
        {1.0f, 0.0313725508749f, 0.0313725508749f}},
      { // green
        {0.0f, 0.984313726425f, 0.984313726425f},
        {0.125f, 0.921568632126f, 0.921568632126f},
        {0.25f, 0.858823537827f, 0.858823537827f},
        {0.375f, 0.792156875134f, 0.792156875134f},
        {0.5f, 0.68235296011f, 0.68235296011f},
        {0.625f, 0.572549045086f, 0.572549045086f},
        {0.75f, 0.443137258291f, 0.443137258291f},
        {0.875f, 0.317647069693f, 0.317647069693f},
        {1.0f, 0.188235297799f, 0.188235297799f}},
      { // blue
        {0.0f, 1.0f, 1.0f},
        {0.125f, 0.96862745285f, 0.96862745285f},
        {0.25f, 0.937254905701f, 0.937254905701f},
        {0.375f, 0.882352948189f, 0.882352948189f},
        {0.5f, 0.839215695858f, 0.839215695858f},
        {0.625f, 0.776470601559f, 0.776470601559f},
        {0.75f, 0.709803938866f, 0.709803938866f},
        {0.875f, 0.611764729023f, 0.611764729023f},
        {1.0f, 0.419607847929f, 0.419607847929f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
