// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefPurples {

  private ColorMapDefPurples() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.988235294819f, 0.988235294819f},
        {0.125f, 0.937254905701f, 0.937254905701f},
        {0.25f, 0.854901969433f, 0.854901969433f},
        {0.375f, 0.737254917622f, 0.737254917622f},
        {0.5f, 0.61960786581f, 0.61960786581f},
        {0.625f, 0.501960813999f, 0.501960813999f},
        {0.75f, 0.415686279535f, 0.415686279535f},
        {0.875f, 0.329411774874f, 0.329411774874f},
        {1.0f, 0.247058823705f, 0.247058823705f}},
      { // green
        {0.0f, 0.984313726425f, 0.984313726425f},
        {0.125f, 0.929411768913f, 0.929411768913f},
        {0.25f, 0.854901969433f, 0.854901969433f},
        {0.375f, 0.741176486015f, 0.741176486015f},
        {0.5f, 0.603921592236f, 0.603921592236f},
        {0.625f, 0.490196079016f, 0.490196079016f},
        {0.75f, 0.317647069693f, 0.317647069693f},
        {0.875f, 0.152941182256f, 0.152941182256f},
        {1.0f, 0.0f, 0.0f}},
      { // blue
        {0.0f, 0.992156863213f, 0.992156863213f},
        {0.125f, 0.960784316063f, 0.960784316063f},
        {0.25f, 0.921568632126f, 0.921568632126f},
        {0.375f, 0.86274510622f, 0.86274510622f},
        {0.5f, 0.784313738346f, 0.784313738346f},
        {0.625f, 0.729411780834f, 0.729411780834f},
        {0.75f, 0.639215707779f, 0.639215707779f},
        {0.875f, 0.560784339905f, 0.560784339905f},
        {1.0f, 0.490196079016f, 0.490196079016f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
