// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefPrism {

  private ColorMapDefPrism() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 1.0f, 1.0f},
        {0.031746f, 1.0f, 1.0f},
        {0.047619f, 0.0f, 0.0f},
        {0.063492f, 0.0f, 0.0f},
        {0.079365f, 0.666667f, 0.666667f},
        {0.095238f, 1.0f, 1.0f},
        {0.126984f, 1.0f, 1.0f},
        {0.142857f, 0.0f, 0.0f},
        {0.15873f, 0.0f, 0.0f},
        {0.174603f, 0.666667f, 0.666667f},
        {0.190476f, 1.0f, 1.0f},
        {0.222222f, 1.0f, 1.0f},
        {0.238095f, 0.0f, 0.0f},
        {0.253968f, 0.0f, 0.0f},
        {0.269841f, 0.666667f, 0.666667f},
        {0.285714f, 1.0f, 1.0f},
        {0.31746f, 1.0f, 1.0f},
        {0.333333f, 0.0f, 0.0f},
        {0.349206f, 0.0f, 0.0f},
        {0.365079f, 0.666667f, 0.666667f},
        {0.380952f, 1.0f, 1.0f},
        {0.412698f, 1.0f, 1.0f},
        {0.428571f, 0.0f, 0.0f},
        {0.444444f, 0.0f, 0.0f},
        {0.460317f, 0.666667f, 0.666667f},
        {0.47619f, 1.0f, 1.0f},
        {0.507937f, 1.0f, 1.0f},
        {0.52381f, 0.0f, 0.0f},
        {0.539683f, 0.0f, 0.0f},
        {0.555556f, 0.666667f, 0.666667f},
        {0.571429f, 1.0f, 1.0f},
        {0.603175f, 1.0f, 1.0f},
        {0.619048f, 0.0f, 0.0f},
        {0.634921f, 0.0f, 0.0f},
        {0.650794f, 0.666667f, 0.666667f},
        {0.666667f, 1.0f, 1.0f},
        {0.698413f, 1.0f, 1.0f},
        {0.714286f, 0.0f, 0.0f},
        {0.730159f, 0.0f, 0.0f},
        {0.746032f, 0.666667f, 0.666667f},
        {0.761905f, 1.0f, 1.0f},
        {0.793651f, 1.0f, 1.0f},
        {0.809524f, 0.0f, 0.0f},
        {0.825397f, 0.0f, 0.0f},
        {0.84127f, 0.666667f, 0.666667f},
        {0.857143f, 1.0f, 1.0f},
        {0.888889f, 1.0f, 1.0f},
        {0.904762f, 0.0f, 0.0f},
        {0.920635f, 0.0f, 0.0f},
        {0.936508f, 0.666667f, 0.666667f},
        {0.952381f, 1.0f, 1.0f},
        {0.984127f, 1.0f, 1.0f},
        {1.0f, 0.0f, 0.0f}},
      { // green
        {0.0f, 0.0f, 0.0f},
        {0.031746f, 1.0f, 1.0f},
        {0.047619f, 1.0f, 1.0f},
        {0.063492f, 0.0f, 0.0f},
        {0.095238f, 0.0f, 0.0f},
        {0.126984f, 1.0f, 1.0f},
        {0.142857f, 1.0f, 1.0f},
        {0.15873f, 0.0f, 0.0f},
        {0.190476f, 0.0f, 0.0f},
        {0.222222f, 1.0f, 1.0f},
        {0.238095f, 1.0f, 1.0f},
        {0.253968f, 0.0f, 0.0f},
        {0.285714f, 0.0f, 0.0f},
        {0.31746f, 1.0f, 1.0f},
        {0.333333f, 1.0f, 1.0f},
        {0.349206f, 0.0f, 0.0f},
        {0.380952f, 0.0f, 0.0f},
        {0.412698f, 1.0f, 1.0f},
        {0.428571f, 1.0f, 1.0f},
        {0.444444f, 0.0f, 0.0f},
        {0.47619f, 0.0f, 0.0f},
        {0.507937f, 1.0f, 1.0f},
        {0.52381f, 1.0f, 1.0f},
        {0.539683f, 0.0f, 0.0f},
        {0.571429f, 0.0f, 0.0f},
        {0.603175f, 1.0f, 1.0f},
        {0.619048f, 1.0f, 1.0f},
        {0.634921f, 0.0f, 0.0f},
        {0.666667f, 0.0f, 0.0f},
        {0.698413f, 1.0f, 1.0f},
        {0.714286f, 1.0f, 1.0f},
        {0.730159f, 0.0f, 0.0f},
        {0.761905f, 0.0f, 0.0f},
        {0.793651f, 1.0f, 1.0f},
        {0.809524f, 1.0f, 1.0f},
        {0.825397f, 0.0f, 0.0f},
        {0.857143f, 0.0f, 0.0f},
        {0.888889f, 1.0f, 1.0f},
        {0.904762f, 1.0f, 1.0f},
        {0.920635f, 0.0f, 0.0f},
        {0.952381f, 0.0f, 0.0f},
        {0.984127f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}},
      { // blue
        {0.0f, 0.0f, 0.0f},
        {0.047619f, 0.0f, 0.0f},
        {0.063492f, 1.0f, 1.0f},
        {0.079365f, 1.0f, 1.0f},
        {0.095238f, 0.0f, 0.0f},
        {0.142857f, 0.0f, 0.0f},
        {0.15873f, 1.0f, 1.0f},
        {0.174603f, 1.0f, 1.0f},
        {0.190476f, 0.0f, 0.0f},
        {0.238095f, 0.0f, 0.0f},
        {0.253968f, 1.0f, 1.0f},
        {0.269841f, 1.0f, 1.0f},
        {0.285714f, 0.0f, 0.0f},
        {0.333333f, 0.0f, 0.0f},
        {0.349206f, 1.0f, 1.0f},
        {0.365079f, 1.0f, 1.0f},
        {0.380952f, 0.0f, 0.0f},
        {0.428571f, 0.0f, 0.0f},
        {0.444444f, 1.0f, 1.0f},
        {0.460317f, 1.0f, 1.0f},
        {0.47619f, 0.0f, 0.0f},
        {0.52381f, 0.0f, 0.0f},
        {0.539683f, 1.0f, 1.0f},
        {0.555556f, 1.0f, 1.0f},
        {0.571429f, 0.0f, 0.0f},
        {0.619048f, 0.0f, 0.0f},
        {0.634921f, 1.0f, 1.0f},
        {0.650794f, 1.0f, 1.0f},
        {0.666667f, 0.0f, 0.0f},
        {0.714286f, 0.0f, 0.0f},
        {0.730159f, 1.0f, 1.0f},
        {0.746032f, 1.0f, 1.0f},
        {0.761905f, 0.0f, 0.0f},
        {0.809524f, 0.0f, 0.0f},
        {0.825397f, 1.0f, 1.0f},
        {0.84127f, 1.0f, 1.0f},
        {0.857143f, 0.0f, 0.0f},
        {0.904762f, 0.0f, 0.0f},
        {0.920635f, 1.0f, 1.0f},
        {0.936508f, 1.0f, 1.0f},
        {0.952381f, 0.0f, 0.0f},
        {1.0f, 0.0f, 0.0f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
