// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefPuor {

  private ColorMapDefPuor() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.498039215803f, 0.498039215803f},
        {0.1f, 0.701960802078f, 0.701960802078f},
        {0.2f, 0.878431379795f, 0.878431379795f},
        {0.3f, 0.992156863213f, 0.992156863213f},
        {0.4f, 0.996078431606f, 0.996078431606f},
        {0.5f, 0.96862745285f, 0.96862745285f},
        {0.6f, 0.847058832645f, 0.847058832645f},
        {0.7f, 0.698039233685f, 0.698039233685f},
        {0.8f, 0.501960813999f, 0.501960813999f},
        {0.9f, 0.329411774874f, 0.329411774874f},
        {1.0f, 0.176470592618f, 0.176470592618f}},
      { // green
        {0.0f, 0.23137255013f, 0.23137255013f},
        {0.1f, 0.345098048449f, 0.345098048449f},
        {0.2f, 0.509803950787f, 0.509803950787f},
        {0.3f, 0.721568644047f, 0.721568644047f},
        {0.4f, 0.878431379795f, 0.878431379795f},
        {0.5f, 0.96862745285f, 0.96862745285f},
        {0.6f, 0.854901969433f, 0.854901969433f},
        {0.7f, 0.670588254929f, 0.670588254929f},
        {0.8f, 0.450980395079f, 0.450980395079f},
        {0.9f, 0.152941182256f, 0.152941182256f},
        {1.0f, 0.0f, 0.0f}},
      { // blue
        {0.0f, 0.0313725508749f, 0.0313725508749f},
        {0.1f, 0.0235294122249f, 0.0235294122249f},
        {0.2f, 0.0784313753247f, 0.0784313753247f},
        {0.3f, 0.388235300779f, 0.388235300779f},
        {0.4f, 0.713725507259f, 0.713725507259f},
        {0.5f, 0.96862745285f, 0.96862745285f},
        {0.6f, 0.921568632126f, 0.921568632126f},
        {0.7f, 0.823529422283f, 0.823529422283f},
        {0.8f, 0.674509823322f, 0.674509823322f},
        {0.9f, 0.533333361149f, 0.533333361149f},
        {1.0f, 0.29411765933f, 0.29411765933f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
