// This file is automatically generated by a script (generateColorMaps.py).
// Do not modify it, or changes will be lost when the script is run again.
/*
 * This file was generated using data provided by the python library matplotlib
 * which is Copyright (c) 2002-2004 John D. Hunter; All Rights Reserved
 *
 * For the rest of the code source, the following copyright and license
 * applies.
 *
 * Copyright 2008 The Depan Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.devtools.depan.eclipse.cm;

public final class ColorMapDefGnbu {

  private ColorMapDefGnbu() { }

  public static final float[][][] CM = {
      { // red
        {0.0f, 0.96862745285f, 0.96862745285f},
        {0.125f, 0.878431379795f, 0.878431379795f},
        {0.25f, 0.800000011921f, 0.800000011921f},
        {0.375f, 0.658823549747f, 0.658823549747f},
        {0.5f, 0.482352942228f, 0.482352942228f},
        {0.625f, 0.305882364511f, 0.305882364511f},
        {0.75f, 0.168627455831f, 0.168627455831f},
        {0.875f, 0.0313725508749f, 0.0313725508749f},
        {1.0f, 0.0313725508749f, 0.0313725508749f}},
      { // green
        {0.0f, 0.988235294819f, 0.988235294819f},
        {0.125f, 0.952941179276f, 0.952941179276f},
        {0.25f, 0.921568632126f, 0.921568632126f},
        {0.375f, 0.866666674614f, 0.866666674614f},
        {0.5f, 0.800000011921f, 0.800000011921f},
        {0.625f, 0.701960802078f, 0.701960802078f},
        {0.75f, 0.549019634724f, 0.549019634724f},
        {0.875f, 0.407843142748f, 0.407843142748f},
        {1.0f, 0.250980407f, 0.250980407f}},
      { // blue
        {0.0f, 0.941176474094f, 0.941176474094f},
        {0.125f, 0.858823537827f, 0.858823537827f},
        {0.25f, 0.772549033165f, 0.772549033165f},
        {0.375f, 0.709803938866f, 0.709803938866f},
        {0.5f, 0.768627464771f, 0.768627464771f},
        {0.625f, 0.827450990677f, 0.827450990677f},
        {0.75f, 0.745098054409f, 0.745098054409f},
        {0.875f, 0.674509823322f, 0.674509823322f},
        {1.0f, 0.505882382393f, 0.505882382393f}},
      { // alpha
        {0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}}
      };
}
